const $ = id => document.getElementById(id);
let index=0, busy=false, mistakes=0, attempted=false, firstTry=0, variant=0, position=0, current, timer;
let sessionVariants=[];
function randomVariant(){return 1+Math.floor(Math.random()*5);}
function prepareSession(){sessionVariants=questions.map(()=>randomVariant());}
function parseAnswer(raw){const t=raw.trim();if(!/^\d+(?:[.,]\d+)?$/.test(t))return null;const v=Number(t.replace(',','.'));return Number.isFinite(v)?v:null;}
function progress(count){$('xp').textContent=count*100;$('room-progress').textContent=`${count} / 10 klara`;$('progress-label').textContent=`${count} av 10 uppgifter`;$('steps').innerHTML=questions.map((q,i)=>`<span class="step ${i<count?'done':i===count?'current':''}" aria-label="Uppgift ${i+1}${i<count?', klar':''}">${i<count?'✓':i+1}</span>`).join('');}
function move(){$('student').setAttribute('transform',`translate(${140+position*44} 275)`);}
function render(){if(variant===0) variant=sessionVariants[index]||randomVariant();current=makeQuestion(index,variant);busy=false;$('category').textContent=current.category;$('counter').textContent=`${String(index+1).padStart(2,'0')} / 10`;$('title').textContent=current.title;$('question').textContent=current.text;$('unit').textContent=current.unit;$('answer').value='';$('answer').disabled=false;$('answer').removeAttribute('aria-invalid');$('feedback').textContent='';$('feedback').className='';$('hint-text').hidden=true;$('hint').hidden=false;$('submit').disabled=false;$('submit').textContent='Kontrollera svar ↵';progress(index);move();$('answer').focus();}
function finish(){$('challenge').hidden=true;$('finish').hidden=false;position=10;move();$('lock').textContent='ÖPPEN';$('door').classList.add('open');$('door-status').textContent='Nästa avdelning är upplåst!';$('results').textContent=`${firstTry} nivåer klarade på första försöket · ${mistakes} extra försök`;$('replay').focus();}
$('answer-form').addEventListener('submit',event=>{event.preventDefault();if(busy)return;const value=parseAnswer($('answer').value);if(value===null){$('feedback').textContent='Skriv ett numeriskt svar, till exempel 1,5. Enheten står bredvid.';$('feedback').className='error';$('answer').setAttribute('aria-invalid','true');return;}busy=true;$('submit').disabled=true;$('answer').disabled=true;$('hint').hidden=true;$('hint-text').hidden=true;
if(Math.abs(value-current.answer)<1e-9){if(!attempted)firstTry++;$('feedback').textContent='Rätt! +100 XP';$('feedback').className='success';$('answer').removeAttribute('aria-invalid');$('submit').textContent=index===9?'Dörren öppnas…':'På väg till nästa uppgift…';position=Math.min(10,position+1);move();progress(index+1);timer=setTimeout(()=>{index++;variant=0;attempted=false;if(index===questions.length)finish();else render();},1100);
}else{attempted=true;mistakes++;position=Math.max(-1,position-1);move();$('feedback').textContent=`Fel svar. Ett steg tillbaka. Rätt svar är ${current.answer} ${current.unit}. ${current.solution}`;$('feedback').className='error';$('submit').textContent='Ny uppgift på samma nivå…';timer=setTimeout(()=>{variant++;render();$('feedback').textContent='Ny uppgift, samma svårighetsnivå. Dina XP är kvar.';},2200);}});
$('hint').addEventListener('click',()=>{$('hint-text').textContent=current.hint;$('hint-text').hidden=!$('hint-text').hidden;});
$('replay').addEventListener('click',()=>{clearTimeout(timer);index=0;mistakes=0;firstTry=0;variant=0;position=0;attempted=false;prepareSession();$('finish').hidden=true;$('challenge').hidden=false;$('lock').textContent='LÅST';$('door').classList.remove('open');$('door-status').textContent='Nästa dörr öppnas efter 10 rätt';render();});
prepareSession();
render();
