const $ = id => document.getElementById(id);
let index=0, busy=false, mistakes=0, attempted=false, firstTry=0, variant=0, position=0, current, timer, roomIndex=0;
const rooms=['Medicin- och kirurgavdelningen','Akutvårdsavdelningen','Akutmottagningen','Intensivvårdsavdelningen'];
const roomSigns=['MEDICIN & KIRURGI','AKUTVÅRD','AKUTMOTTAGNING','INTENSIVVÅRD'];
const roomEvents=['Läkemedelsvagnen behöver dubbelkontrolleras.','Ett akutlarm väntar i korridoren.','Nytt larm: nästa patient väntar.','Övervakningen piper – kontrollera beräkningen.'];
let sessionVariants=[], audioContext=null, musicTimer=null, musicOn=false, musicStep=0;
const musicNotes=[261.63,329.63,392,329.63,293.66,349.23,440,349.23], musicOctaves=[0,1,2,1];
function randomVariant(){return 1+Math.floor(Math.random()*8)}
function prepareSession(){sessionVariants=questions.map(()=>randomVariant())}
function getAudioContext(){const AudioCtx=globalThis.AudioContext||globalThis.webkitAudioContext;if(!AudioCtx)return null;if(!audioContext)audioContext=new AudioCtx();if(audioContext.state==='suspended')audioContext.resume();return audioContext}
function playNote(){if(!musicOn||!audioContext)return;const now=audioContext.currentTime,osc=audioContext.createOscillator(),gain=audioContext.createGain(),note=musicNotes[musicStep%musicNotes.length],octave=musicOctaves[Math.floor(musicStep/musicNotes.length)%musicOctaves.length];osc.type='sine';osc.frequency.value=note*Math.pow(2,octave);gain.gain.setValueAtTime(0,now);gain.gain.linearRampToValueAtTime(.045,now+.08);gain.gain.exponentialRampToValueAtTime(.001,now+1.7);osc.connect(gain).connect(audioContext.destination);osc.start(now);osc.stop(now+1.8);musicStep++}
function toggleMusic(){if(!getAudioContext())return;musicOn=!musicOn;const b=$('music-toggle');b.setAttribute('aria-pressed',String(musicOn));b.textContent=musicOn?'♫ Musik på':'♫ Musik av';if(musicOn){playNote();musicTimer=setInterval(playNote,900)}else{clearInterval(musicTimer);musicTimer=null}}
function playSuccessSound(){const ctx=getAudioContext();if(!ctx)return;const now=ctx.currentTime;[523.25,659.25,783.99].forEach((frequency,i)=>{const osc=ctx.createOscillator(),gain=ctx.createGain();osc.type='triangle';osc.frequency.value=frequency;gain.gain.setValueAtTime(0,now+i*.09);gain.gain.linearRampToValueAtTime(.08,now+i*.09+.025);gain.gain.exponentialRampToValueAtTime(.001,now+i*.09+.42);osc.connect(gain).connect(ctx.destination);osc.start(now+i*.09);osc.stop(now+i*.09+.45)})}
function playFailSound(){const ctx=getAudioContext();if(!ctx)return;const now=ctx.currentTime;[220,165].forEach((frequency,i)=>{const osc=ctx.createOscillator(),gain=ctx.createGain();osc.type='sine';osc.frequency.value=frequency;gain.gain.setValueAtTime(.001,now+i*.12);gain.gain.linearRampToValueAtTime(.045,now+i*.12+.02);gain.gain.exponentialRampToValueAtTime(.001,now+i*.12+.28);osc.connect(gain).connect(ctx.destination);osc.start(now+i*.12);osc.stop(now+i*.12+.3)})}
function parseAnswer(raw){const t=raw.trim();if(!/^\d+(?:[.,]\d+)?$/.test(t))return null;const v=Number(t.replace(',','.'));return Number.isFinite(v)?v:null}
function progress(count){$('xp').textContent=roomIndex*1000+count*100;$('room-progress').textContent=`${count} / 10 steg`;$('progress-label').textContent=`${count} av 10 steg`;$('steps').innerHTML=questions.map((q,i)=>`<span class="step ${i<count?'done':i===count?'current':''}" aria-label="Steg ${i+1}${i<count?', klart':''}">${i<count?'✓':i+1}</span>`).join('')}
function move(){$('student').setAttribute('transform',`translate(${140+position*44} 275)`)}
function animateStudent(type){const x=140+position*44,y=275,s=$('student');if(s._motion)s._motion.cancel();const frames=type==='success'?[{transform:`translate(${x}px,${y}px) scale(1)`},{transform:`translate(${x}px,${y-18}px) scale(1.05)`},{transform:`translate(${x+18}px,${y-8}px) scale(1.02)`},{transform:`translate(${x}px,${y}px) scale(1)`}]:[{transform:`translate(${x}px,${y}px) rotate(0deg)`},{transform:`translate(${x+10}px,${y+3}px) rotate(18deg)`},{transform:`translate(${x-4}px,${y}px) rotate(-12deg)`},{transform:`translate(${x}px,${y}px) rotate(0deg)`}];s._motion=s.animate(frames,{duration:700,easing:'ease-out'});s._motion.onfinish=()=>{s.style.transform='';s.setAttribute('transform',`translate(${x} ${y})`);s._motion=null}}
function render(){if(variant===0)variant=sessionVariants[index]||randomVariant();current=makeQuestion(index,variant,roomIndex);busy=false;document.body.dataset.room=String(roomIndex);$('room-name').textContent=rooms[roomIndex];$('room-badge').textContent=`BANA ${String(roomIndex+1).padStart(2,'0')}`;$('ward-sign-text').textContent=roomSigns[roomIndex];$('door-label').textContent=roomIndex<rooms.length-1?rooms[roomIndex+1].toUpperCase():'MÅL';$('category').textContent=current.category;$('counter').textContent=`STEG ${String(position+1).padStart(2,'0')} / 10`;$('title').textContent=current.title;$('question').textContent=current.text;$('unit').textContent=current.unit;$('answer').value='';$('answer').disabled=false;$('answer').removeAttribute('aria-invalid');$('feedback').textContent='';$('feedback').className='';$('hint-text').hidden=true;$('hint').hidden=false;$('submit').disabled=false;$('submit').textContent='Kontrollera svar ↵';progress(position);move();$('answer').focus()}
function finish(){$('challenge').hidden=true;$('finish').hidden=false;move();$('lock').textContent='ÖPPEN';$('door').classList.add('open');$('results').textContent=`${firstTry} steg klarade på första försöket · ${mistakes} extra försök`;$('finish-xp').textContent=`${(roomIndex+1)*1000} XP`;$('replay').focus();if(roomIndex<rooms.length-1){$('finish-title').textContent=`${rooms[roomIndex]} avklarad!`;$('finish-copy').textContent=`Du har nått dörren och öppnat vägen till ${rooms[roomIndex+1]}.`;$('coming').textContent=`Nästa: ${rooms[roomIndex+1]}`;$('next-room').hidden=false;$('door-status').textContent='Nästa avdelning är upplåst!'}else{$('finish-title').textContent='Hela resan avklarad!';$('finish-copy').textContent='Du har tagit dig genom alla fyra avdelningar.';$('coming').textContent='Alla avdelningar är öppna.';$('next-room').hidden=true;$('door-status').textContent='Sjukhusresan är klar!'}}
$('answer-form').addEventListener('submit',event=>{event.preventDefault();if(busy)return;const value=parseAnswer($('answer').value);if(value===null){$('feedback').textContent='Skriv ett numeriskt svar, till exempel 1,5. Enheten står bredvid.';$('feedback').className='error';$('answer').setAttribute('aria-invalid','true');return}busy=true;$('submit').disabled=true;$('answer').disabled=true;$('hint').hidden=true;$('hint-text').hidden=true;if(Math.abs(value-current.answer)<1e-9){if(!attempted)firstTry++;$('feedback').textContent='Rätt! +100 XP';$('feedback').className='success';$('submit').textContent=position===9?'Dörren öppnas…':'Ett steg framåt…';position=Math.min(10,position+1);move();progress(position);if(position===10)timer=setTimeout(finish,1100);else timer=setTimeout(()=>{index=position;variant=0;attempted=false;render()},1100)}else{attempted=true;mistakes++;position=Math.max(0,position-1);move();$('feedback').textContent=`Fel svar. Ett steg tillbaka. Rätt svar är ${current.answer} ${current.unit}. ${current.solution}`;$('feedback').className='error';$('submit').textContent='Ny uppgift på samma nivå…';timer=setTimeout(()=>{index=position;variant++;render();$('feedback').textContent='Ny uppgift, samma svårighetsnivå. Dina XP är kvar.'},2200)}})
$('hint').addEventListener('click',()=>{$('hint-text').textContent=current.hint;$('hint-text').hidden=!$('hint-text').hidden});
$('music-toggle').addEventListener('click',toggleMusic);
$('answer-form').addEventListener('submit',()=>{if($('feedback').className==='success')playSuccessSound()});
$('answer-form').addEventListener('submit',()=>{if($('feedback').className==='error'&&$('answer').disabled)playFailSound()});
$('answer-form').addEventListener('submit',()=>{if($('feedback').className==='success')animateStudent('success');if($('feedback').className==='error'&&$('answer').disabled)animateStudent('fail')});
$('answer-form').addEventListener('submit',()=>{if($('feedback').className==='error'&&$('answer').disabled){$('event-text').textContent=`LARMNIVÅ ÖKAR · ${roomEvents[roomIndex]}`;$('event-banner').hidden=false}});
$('next-room').addEventListener('click',()=>{clearTimeout(timer);roomIndex++;index=0;mistakes=0;firstTry=0;variant=0;position=0;attempted=false;prepareSession();$('finish').hidden=true;$('challenge').hidden=false;$('lock').textContent='LÅST';$('door').classList.remove('open');$('door-status').textContent='Nästa dörr öppnas efter 10 rätt';render()});
$('replay').addEventListener('click',()=>{clearTimeout(timer);index=0;mistakes=0;firstTry=0;variant=0;position=0;attempted=false;prepareSession();$('finish').hidden=true;$('challenge').hidden=false;$('lock').textContent='LÅST';$('door').classList.remove('open');$('door-status').textContent='Nästa dörr öppnas efter 10 rätt';render()});
const originalRender=render;
render=function(){originalRender();$('location-label').textContent=`● Du är här · ${rooms[roomIndex]}`;$('event-banner').hidden=true};
prepareSession();render();
